#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

typedef char RCP_INT8;
typedef unsigned char RCP_UINT8;
typedef short RCP_INT16;
typedef unsigned short RCP_UINT16;
typedef int RCP_INT32;
typedef unsigned int RCP_UINT32;
typedef unsigned long long RCP_UINT64;
typedef float RCP_FLOAT;
typedef double RCP_DOUBLE;
typedef unsigned char RCP_BOOL;

#define RCP_NISAC_V1	0xCC
#define RCP_NISAC_V2	0xC2
#define RCP_NISAC_V3	0xD1
#define RCP_NISAC_Y2	0xC5

/*
  *	Define command type macro
  */
typedef enum {
	/* rcp rule add related */
	ADD_IPV4_FIVE_TUPLE = 0,
	ADD_IPV4_FIVE_TUPLE_ACK,
	ADD_IPV6_FIVE_TUPLE,
	ADD_IPV6_FIVE_TUPLE_ACK,
	ADD_TCP_FLAG,
	ADD_TCP_FLAG_ACK,
	ADD_UD,
	ADD_UD_ACK,

	/* rcp connect related */
	CONNECT_REQUEST,
	CONNECT_REQUEST_ACK,
	QUIT_REQUEST,
	QUIT_REQUEST_ACK,

	/* rcp rule query related */
	QUERY_IPV4_FIVE_TUPLE,
	QUERY_IPV4_FIVE_TUPLE_ACK,
	QUERY_IPV6_FIVE_TUPLE,
	QUERY_IPV6_FIVE_TUPLE_ACK,
	QUERY_TCP_FLAG,
	QUERY_TCP_FLAG_ACK,
	QUERY_UD,
	QUERY_UD_ACK,

	/* rcp rule list related */
	QUERY_ALL_IPV4_FIVE_TUPLE_RULE_NUM,
	QUERY_ALL_IPV6_FIVE_TUPLE_RULE_NUM,
	QUERY_ALL_IPV4_COMPOUND_RULE_NUM,
	QUERY_ALL_IPV6_COMPOUND_RULE_NUM,
	QUERY_ALL_TCP_FLAG_RULE_NUM,
	QUERY_ALL_RULE_NUM,
	QUERY_RULE_NUM_ACK,
	QUERY_ALL_IPV4_FIVE_TUPLE,
	QUERY_ALL_IPV4_FIVE_TUPLE_ACK,
	QUERY_ALL_IPV6_FIVE_TUPLE,
	QUERY_ALL_IPV6_FIVE_TUPLE_ACK,
	QUERY_ALL_TCP_FLAG_RULE,
	QUERY_ALL_TCP_FLAG_RULE_ACK,
	QUERY_ALL_UD,
	QUERY_ALL_UD_ACK,

	/* rcp rule del related */
	DEL_ONE_IPV4_FIVE_TUPLE,
	DEL_ONE_IPV4_FIVE_TUPLE_ACK,
	DEL_ONE_IPV6_FIVE_TUPLE,
	DEL_ONE_IPV6_FIVE_TUPLE_ACK,
	DEL_ONE_TCP_FLAG,
	DEL_ONE_TCP_FLAG_ACK,
	DEL_ONE_UD,
	DEL_ONE_UD_ACK,
	DEL_ALL_RULE,
	DEL_ALL_RULE_ACK,
	DEL_RULE_TYPE_ALL,
	DEL_RULE_TYPE_ALL_ACK,

	/* cli connect related */
	CLI_USER_REGISTER,
	CLI_USER_REGISTER_ACK,
	CLI_GET_USER_INFO,
	CLI_GET_USER_INFO_ACK,

	/* cli system related command */
	SHOW_SYSTEM,
	SHOW_SYSTEM_ACK,
	SHOW_CONFIG,
	SHOW_CONFIG_ACK,
	SHOW_RULE,
	SHOW_RULE_ACK,
	SHOW_RULE_BY_TYPE,
	SHOW_RULE_BY_TYPE_ACK,
	SHOW_RULE_HIT_BY_TYPE,
	SHOW_RULE_HIT_BY_TYPE_ACK,
	SHOW_USER_ACCESS,
	SHOW_USER_ACCESS_ACK,
	SET_USER_PASSWD,
	SET_USER_PASSWD_ACK,
	SHOW_USER_PASSWD,
	SHOW_USER_PASSWD_ACK,
	SET_USER,
	SET_USER_ACK,
	SET_USER_LOGINTOOL,
	SET_USER_LOGINTOOL_ACK,
	RESET_USER_PASSWD,
	RESET_USER_PASSWD_ACK,
	SET_USER_DESCR,
	SET_USER_DESCR_ACK,
	SAVE_CONFIG,
	SAVE_CONFIG_ACK,
	SET_TEMPERATURE,
	SET_TEMPERATURE_ACK, 
	RESTORE_CONFIG,
	RESTORE_CONFIG_ACK,
	SET_CONNECT_MAX,
	SET_CONNECT_MAX_ACK,
	SHOW_CONNECT_MAX,
	SHOW_CONNECT_MAX_ACK,
	SHOW_DIFF_WITH_WEB,
	SHOW_DIFF_WITH_WEB_ACK,
	SYNC_FROM_WEB,
	SYNC_FROM_WEB_ACK,
	GET_SYNC_FROM_WEB_STATUS,
	GET_SYNC_FROM_WEB_STATUS_ACK,
	SET_REAL_TIME_BACKUP,
	SET_REAL_TIME_BACKUP_ACK,
	SHOW_AUTOBIND_STATUS,
	SHOW_AUTOBIND_STATUS_ACK,
	SET_TRUSTED_HOSTIP_ABLE,
	SET_TRUSTED_HOSTIP_ABLE_ACK,
	ADD_TRUSTED_HOSTIP,
	ADD_TRUSTED_HOSTIP_ACK,
	DEL_TRUSTED_HOSTIP,
	DEL_TRUSTED_HOSTIP_ACK,
    SET_NTP,
    SET_NTP_ACK,
	SHOW_NTP_CONFIG,
    SHOW_NTP_CONFIG_ACK,
	SHOW_AIR_FAN_STATUS,
	SHOW_AIR_FAN_STATUS_ACK,
	SHOW_POWER_STATUS,
	SHOW_POWER_STATUS_ACK,
  	SET_CHASSIS_FAN_LEVEL,
	SET_CHASSIS_FAN_LEVEL_ACK,
	SHOW_CHASSIS_FAN_LEVEL,
	SHOW_CHASSIS_FAN_LEVEL_ACK,
	SET_SUBSYSTEM_SYSTEM_MODE,
	SET_SUBSYSTEM_SYSTEM_MODE_ACK,
	SET_DPT_DD_MODE_ABLE,
	SET_DPT_DD_MODE_ABLE_ACK,
	SET_SNMP_CHASSIS_IP,
	SET_SNMP_CHASSIS_IP_ACK,
	SET_SNMP_CHASSIS_DESCR,
	SET_SNMP_CHASSIS_DESCR_ACK,
	CLEAR_SNMP_CHASSIS_IP_MORE,
	CLEAR_SNMP_CHASSIS_IP_MORE_ACK,
	GET_SNMP_CHASSIS_INFO,
	GET_SNMP_CHASSIS_INFO_ACK,
    SET_SNMP_CHASSIS_IF_DESCR,
    SET_SNMP_CHASSIS_IF_DESCR_ACK,
    GET_SNMP_CHASSIS_IF_DESCR,
    GET_SNMP_CHASSIS_IF_DESCR_ACK,
    SET_SNMP_CHASSIS_IF_SMAC,
    SET_SNMP_CHASSIS_IF_SMAC_ACK,
    GET_SNMP_CHASSIS_IF_SMAC,
    GET_SNMP_CHASSIS_IF_SMAC_ACK,
    SET_SNMP_CHASSIS_IF_DMAC,
    SET_SNMP_CHASSIS_IF_DMAC_ACK,
    GET_SNMP_CHASSIS_IF_DMAC,
    GET_SNMP_CHASSIS_IF_DMAC_ACK,

    SET_CHASSIS_IP,
    SET_CHASSIS_IP_ACK,
    SET_CHASSIS_NUM,
    SET_CHASSIS_NUM_ACK,
    SHOW_CHASSIS_STATUS,
    SHOW_CHASSIS_STATUS_ACK,
    GET_CHASSIS_NUM,
    GET_CHASSIS_NUM_ACK,
    GET_CHASSIS_IP,
    GET_CHASSIS_IP_ACK,
    GET_CHASSIS_SUBSYSTEM_INFO,
    GET_CHASSIS_SUBSYSTEM_INFO_ACK,
    SET_CHASSIS_DESCR,
    SET_CHASSIS_DESCR_ACK,
    GET_CHASSIS_DESCR,
    GET_CHASSIS_DESCR_ACK,
    SET_CHASSIS_MODE,
    SET_CHASSIS_MODE_ACK,
    SET_CHASSIS_IP_MORE,
    SET_CHASSIS_IP_MORE_ACK,
    CLEAR_CHASSIS_IP_MORE,
    CLEAR_CHASSIS_IP_MORE_ACK,
    SET_CHASSIS_OUTGROUP,
    SET_CHASSIS_OUTGROUP_ACK,
    SET_DPT_ERROR_CONTINUE,
    SET_DPT_ERROR_CONTINUE_ACK,

	ADD_NODE_APP_URL,
	ADD_NODE_APP_URL_ACK,
	ADD_OM_APP_URL,
	ADD_OM_APP_URL_ACK,
	DEL_NODE_APP_VERSION,
	DEL_NODE_APP_VERSION_ACK,
	DEL_OM_APP_VERSION,
	DEL_OM_APP_VERSION_ACK,
	SET_SLOT_APP_ABLE,
	SET_SLOT_APP_ABLE_ACK,
	SET_OM_APP_ABLE,
	SET_OM_APP_ABLE_ACK,
	SHOW_AVAILABLE_APP_VERSION,
	SHOW_AVAILABLE_APP_VERSION_ACK,
	SHOW_NODE_APP_VERSION,
	SHOW_NODE_APP_VERSION_ACK,
	SHOW_OM_APP_VERSION,
	SHOW_OM_APP_VERSION_ACK,
	UPDATE_OM_BOTTOM_APP,
	UPDATE_OM_BOTTOM_APP_ACK,
	UPDATE_NODE_BOTTOM_APP,
	UPDATE_NODE_BOTTOM_APP_ACK,
	GET_UPDATE_APP_RESULT,
	GET_UPDATE_APP_RESULT_ACK,
	
	SET_PORT_SWITCH_MODE,
	SET_PORT_SWITCH_MODE_ACK,
	SHOW_PORT_SWITCH_MODE,
	SHOW_PORT_SWITCH_MODE_ACK,
	SET_PORT_FLEXIBLE_MODE,
	SET_PORT_FLEXIBLE_MODE_ACK,
    SET_SYSTEM_HASH,
    SET_SYSTEM_HASH_ACK,

	/* cli rule related command */
	SHOW_USER_RESOURCE_ALLOCATION,
	SHOW_USER_RESOURCE_ALLOCATION_ACK,
	ADD_RULE,
	ADD_RULE_ACK,
	DEL_RULE,
	DEL_RULE_ACK,
	CHECK_RULE,
	CHECK_RULE_ACK,
	SHOW_USER_RULE_HIT_NUM,
    SHOW_USER_RULE_HIT_NUM_ACK,
    CLEAR_RULE_HIT_NUM,
    CLEAR_RULE_HIT_NUM_ACK,
    GET_RULE_HIT_NUM_BY_CUS_RID,
    GET_RULE_HIT_NUM_BY_CUS_RID_ACK,
    GET_PORT_FLOW_TRAP,
    GET_PORT_FLOW_TRAP_ACK,    
	SET_FLOAT_UD_RULE_APPLY,
	SET_FLOAT_UD_RULE_APPLY_ACK,
	SET_IP_SEARCH_MODE,
	SET_IP_SEARCH_MODE_ACK,
	SET_NOMASK_RULE_COMPLEX,
	SET_NOMASK_RULE_COMPLEX_ACK,
	ALLOC_RULE_ENTRYNUM_APPLY,
	ALLOC_RULE_ENTRYNUM_APPLY_ACK,
	ALLOC_RULE_ENTRYNUM_DEFAULT,
	ALLOC_RULE_ENTRYNUM_DEFAULT_ACK,
	ALLOC_USER_RULE_TYPE_ENTRYNUM,
	ALLOC_USER_RULE_TYPE_ENTRYNUM_ACK,
	SHOW_RULE_NOMASK_CONFIG,
	SHOW_RULE_NOMASK_CONFIG_ACK,
	DEL_RULE_ID,
	DEL_RULE_ID_ACK,
	SET_STRING_RULE_MINLEN,
	SET_STRING_RULE_MINLEN_ACK,
	SET_STRING_RULE_APPLY,
	SET_STRING_RULE_APPLY_ACK,
	SET_RULE_SAFE_MODE,
	SET_RULE_SAFE_MODE_ACK,
	SET_RULE_SAFE_FLOW_THRESHOLD,
	SET_RULE_SAFE_FLOW_THRESHOLD_ACK,
	SET_MAX_DPT_RULE_ID,
	SET_MAX_DPT_RULE_ID_ACK,
	START_RULE,
	START_RULE_ACK,
	STOP_RULE,
	STOP_RULE_ACK,
	SET_RULE_AGING_ABLE,
	SET_RULE_AGING_ABLE_ACK,
	SHOW_USER_UUID_INFO,
	SHOW_USER_UUID_INFO_ACK,
	SHOW_USER_RULE_INFO,
	SHOW_USER_RULE_INFO_ACK,
    SHOW_USER_RULE_COUNTER_INFO,
    SHOW_USER_RULE_COUNTER_INFO_ACK,
	SHOW_USER_ALL_DPT_RULE_ID,
	SHOW_USER_ALL_DPT_RULE_ID_ACK,
    SET_VLAN_SEARCH_MODE,
    SET_VLAN_SEARCH_MODE_ACK,
	SHOW_USER_TASK_RULE_INFO,
	SHOW_USER_TASK_RULE_INFO_ACK,

	/* cli interface related command */
    SET_INTERFACE_FORCE_UP,
    SET_INTERFACE_FORCE_UP_ACK,
    SET_INTERFACE_FLOW_THRESHOLD,
    SET_INTERFACE_FLOW_THRESHOLD_ACK,
    GET_INTERFACE_PERMIT,
    GET_INTERFACE_PERMIT_ACK,

	/* cli action related command */
	ALLOC_USER_OUTPORT,
	ALLOC_USER_OUTPORT_ACK,
	ALLOC_USER_OUTPORT_NONE,
	ALLOC_USER_OUTPORT_NONE_ACK,
	ALLOC_USER_ACTION,
	ALLOC_USER_ACTION_ACK,
	ADD_OUTGROUP,
	ADD_OUTGROUP_ACK,
	DEL_OUTGROUP,
	DEL_OUTGROUP_ACK,
	DEL_OUTGROUP_ALL,
	DEL_OUTGROUP_ALL_ACK,
	SET_OUTGROUP_HASHMODE,
	SET_OUTGROUP_HASHMODE_ACK,
    SET_ACTION_HASHMODE_OUTGROUP,
    SET_ACTION_HASHMODE_OUTGROUP_ACK,
    DEFAULT_ACTION,
    DEFAULT_ACTION_ACK,

	SET_USER_AUTOBIND_ENABLE,
	SET_USER_AUTOBIND_ENABLE_ACK,
	SET_USER_AUTOBIND_AGING_TIME,
	SET_USER_AUTOBIND_AGING_TIME_ACK,
	SET_AUTOBIND_MAX_NUM,
	SET_AUTOBIND_MAX_NUM_ACK,
	SET_USER_AUTOBIND_TABLE_ID,
	SET_USER_AUTOBIND_TABLE_ID_ACK,
	SET_AUTOBIND_TRAP_SCAN_TIME,
	SET_AUTOBIND_TRAP_SCAN_TIME_ACK,
	SET_USER_AUTOBIND_AGING_ENABLE,
	SET_USER_AUTOBIND_AGING_ENABLE_ACK,
	CLEAR_AUTOBIND_REAL_NUM,
	CLEAR_AUTOBIND_REAL_NUM_ACK,
	SET_AUTOBIND_MAX_FW_PACKET,
	SET_AUTOBIND_MAX_FW_PACKET_ACK,
	SET_AUTOBIND_MAX_FW_PACKET_ABLE,
	SET_AUTOBIND_MAX_FW_PACKET_ABLE_ACK,
	SHOW_AUTOBIND_REAL_NUM,
	SHOW_AUTOBIND_REAL_NUM_ACK,
	SHOW_USER_AUTOBIND_STATUS,
	SHOW_USER_AUTOBIND_STATUS_ACK,

	SET_STRIP_HEAD_ENABLE,
	SET_STRIP_HEAD_ENABLE_ACK,
	SET_ALL_OUTGROUP_HASHMODE,
	SET_ALL_OUTGROUP_HASHMODE_ACK,
	SET_USER_HASHMODE,
	SET_USER_HASHMODE_ACK,
	SET_ACTION_FW_FRONT,
	SET_ACTION_FW_FRONT_ACK,
    ADD_INGROUP,
    ADD_INGROUP_ACK,
    DEL_INGROUP,
    DEL_INGROUP_ACK,
    DEL_INGROUP_ALL,
    DEL_INGROUP_ALL_ACK,

    /* cli debug related command */
    SET_DEBUG_LEVEL,
    SET_DEBUG_LEVEL_ACK,
    SET_DEBUG_PRINT,
    SET_DEBUG_PRINT_ACK,
    SET_DEBUG_FILE,
    SET_DEBUG_FILE_ACK,
    SET_DEBUG_FILE_SIZE,
    SET_DEBUG_FILE_SIZE_ACK,    
    SHOW_DEBUG_CONFIG,
    SHOW_DEBUG_CONFIG_ACK,
	SHOW_DEBUG_PUB_RULE_NUM,
	SHOW_DEBUG_PUB_RULE_NUM_ACK,
	SET_DEBUG_PUB_RULE_NUM,
	SET_DEBUG_PUB_RULE_NUM_ACK,
	SET_DEBUG_RULE_RANK_SORT_ABLE,
	SET_DEBUG_RULE_RANK_SORT_ABLE_ACK,
	SHOW_TABLE_ENTRY_NUMBER,
	SHOW_TABLE_ENTRY_NUMBER_ACK,
	SHOW_DEBUG_OUTGROUP_HIT_NUM,
	SHOW_DEBUG_OUTGROUP_HIT_NUM_ACK,
	SHOW_DEBUG_ACTION_HIT_NUM,
	SHOW_DEBUG_ACTION_HIT_NUM_ACK,
	CLEAR_DEBUG_ACTION_HIT_NUM,
	CLEAR_DEBUG_ACTION_HIT_NUM_ACK,

	/* cli log related command */
	SHOW_USER_LOG,
	SHOW_USER_LOG_ACK,
	SET_LOG_TIMEFORMAT,
	SET_LOG_TIMEFORMAT_ACK,
	SET_LOG_ENABLE,
	SET_LOG_ENABLE_ACK,
	SET_LOG_MIBINFO,
	SET_LOG_MIBINFO_ACK,
	SET_LOG_FILESIZE,
	SET_LOG_FILESIZE_ACK,
	SET_LOG_FTP,
	SET_LOG_FTP_ACK,
	SET_LOG_SYSLOG,
	SET_LOG_SYSLOG_ACK,
	SHOW_LOG_CONFIG,
	SHOW_LOG_CONFIG_ACK,
	SET_TRAP_LOG_EN_SW,
	SET_TRAP_LOG_EN_SW_ACK,

	/* cli snmp related command */
	SET_SNMP_OPTION,
	SET_SNMP_OPTION_ACK,
	SHOW_SNMP_STATUS,
	SHOW_SNMP_STATUS_ACK,
	SHOW_SNMP_CONFIG,
	SHOW_SNMP_CONFIG_ACK,
	SET_SNMP_CONFIG,
	SET_SNMP_CONFIG_ACK,

    GET_CAM_INIT_RESULT,
    GET_CAM_INIT_RESULT_ACK,
    GET_CAM_APPLY_RESULT,
    GET_CAM_APPLY_RESULT_ACK,

    SET_DEBUG_DATA,
    SET_DEBUG_DATA_ACK,
    SHOW_DEBUG_DATA,
    SHOW_DEBUG_DATA_ACK,
    SHOW_SYNC_STATUS,
    SHOW_SYNC_STATUS_ACK,

	RCP_NISAC_SHOW_SYSTEM,
	RCP_NISAC_SHOW_SYSTEM_ACK,
	RCP_NISAC_SHOW_CONFIG,
	RCP_NISAC_SHOW_CONFIG_ACK,
	RCP_NISAC_RESTORE_CONFIG,
	RCP_NISAC_RESTORE_CONFIG_ACK,
	RCP_NISAC_SHOW_USER_LOG,
	RCP_NISAC_SHOW_USER_LOG_ACK,


	CHECK_RULE_ID,
	CHECK_RULE_ID_ACK,

	MAX_COMMAND_TYPE
} cmd_type_t;

typedef enum _msg_type_e {
	MSG_TYPE_RCP_CONNECT = 0x01, 
	MSG_TYPE_RCP_RULE_ADD = 0x02, 
	MSG_TYPE_RCP_RULE_QUERY = 0x03, 
	MSG_TYPE_RCP_RULE_LIST = 0x04, 
	MSG_TYPE_RCP_RULE_DEL = 0x05, 
	//MSG_TYPE_RCP_POLICY_SET = 0x06, 

	MSG_TYPE_CLI_CONNECT = 0x11, 
	MSG_TYPE_CLI_SYSTEM = 0x12, 
	MSG_TYPE_CLI_RULE = 0x13, 
	MSG_TYPE_CLI_INTERFACE = 0x14, 
	MSG_TYPE_CLI_OCTEN = 0x15, 
	MSG_TYPE_CLI_DEBUG = 0x16,
	MSG_TYPE_CLI_LOG = 0x17,
	MSG_TYPE_CLI_SNMP = 0x18,
} msg_type_e;

typedef enum _msg_code_e { 
	MSG_CODE_START = 0x0, 
	MSG_CODE_CONNECT = 0x0101, 
	MSG_CODE_CONNECT_ACK = 0x0102, 
	MSG_CODE_QUIT = 0x0103, 
	MSG_CODE_QUIT_ACK = 0x0104,

	MSG_CODE_ADD_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x0201,
	MSG_CODE_ADD_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x0202, 
	MSG_CODE_ADD_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x0203, 
	MSG_CODE_ADD_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x0204, 
	MSG_CODE_ADD_TCP_FLAG_AND_PAYLOAD_LEN_RULE_REQ = 0x0205, 
	MSG_CODE_ADD_TCP_FLAG_AND_PAYLOAD_LEN_RULE_RES = 0x0206, 
	MSG_CODE_ADD_UD_RULE_REQ = 0x0207, 
	MSG_CODE_ADD_UD_RULE_RES = 0x0208,

	MSG_CODE_QUERY_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x0301, 
	MSG_CODE_QUERY_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x0302, 
	MSG_CODE_QUERY_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x0303, 
	MSG_CODE_QUERY_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x0304, 
	MSG_CODE_QUERY_TCP_FLAG_AND_PAYLOAD_LEN_RULE_REQ = 0x0305, 
	MSG_CODE_QUERY_TCP_FLAG_AND_PAYLOAD_LEN_RULE_RES = 0x0306, 
	MSG_CODE_QUERY_UD_RULE_REQ = 0x0307, 
	MSG_CODE_QUERY_UD_RULE_RES = 0x0308,


	MSG_CODE_QUERY_ALL_IPV4_FIVE_TUPLE_RULE_NUM_REQ = 0x0401, 
	MSG_CODE_QUERY_ALL_IPV6_FIVE_TUPLE_RULE_NUM_REQ = 0x0402, 
	MSG_CODE_QUERY_ALL_IPV4_COMPOUND_RULE_NUM_REQ = 0x0403, 
	MSG_CODE_QUERY_ALL_IPV6_COMPOUND_RULE_NUM_REQ = 0x0404, 
	MSG_CODE_QUERY_ALL_TCP_FLAG_AND_PAYLOAD_LEN_RULE_NUM_REQ = 0x0405, 
	MSG_CODE_QUERY_ALL_RULE_NUM_REQ = 0x0406, 
	MSG_CODE_QUERY_RULE_NUM_RES = 0x0407, 
	MSG_CODE_QUERY_ALL_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x0408, 
	MSG_CODE_QUERY_ALL_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x0409, 
	MSG_CODE_QUERY_ALL_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x040A, 
	MSG_CODE_QUERY_ALL_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x040B, 
	MSG_CODE_QUERY_ALL_TCP_FLAG_AND_PAYLOAD_LEN_RULE_REQ = 0x040C, 
	MSG_CODE_QUERY_ALL_TCP_FLAG_AND_PAYLOAD_LEN_RULE_RES = 0x040D, 
	MSG_CODE_QUERY_ALL_UD_RULE_REQ = 0x040E, 
	MSG_CODE_QUERY_ALL_UD_RULE_RES = 0x040F, 

	MSG_CODE_DEL_ONE_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x0501, 
	MSG_CODE_DEL_ONE_IPV4_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x0502, 
	MSG_CODE_DEL_ONE_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_REQ = 0x0503, 
	MSG_CODE_DEL_ONE_IPV6_FIVE_TUPLE_AND_COMPOUND_RULE_RES = 0x0504, 
	MSG_CODE_DEL_ONE_TCP_FLAG_AND_PAYLOAD_LEN_RULE_REQ = 0x0505, 
	MSG_CODE_DEL_ONE_TCP_FLAG_AND_PAYLOAD_LEN_RULE_RES = 0x0506, 
	MSG_CODE_DEL_ONE_UD_RULE_REQ = 0x0507, 
	MSG_CODE_DEL_ONE_UD_RULE_RES = 0x0508, 

	MSG_CODE_DEL_ALL_RULE_REQ = 0x050D, 
	MSG_CODE_DEL_ALL_RULE_RES = 0x050E,  
	MSG_CODE_DEL_RULE_TYPE_ALL_REQ = 0x0510, 
	MSG_CODE_DEL_RULE_TYPE_ALL_RES = 0x0511,  

	MSG_CODE_CLI_USER_REGISTER = 0x701, 
	MSG_CODE_CLI_USER_REGISTER_ACK = 0x702, 
	MSG_CODE_CLI_GET_USER_INFO = 0x703,
	MSG_CODE_CLI_GET_USER_INFO_ACK = 0x703,

	MSG_CODE_SHOW_SYSTEM = 0x801,
	MSG_CODE_SHOW_SYSTEM_ACK = 0x802,
 	MSG_CODE_SET_USER_PASSWD = 0x807,
	MSG_CODE_SET_USER_PASSWD_ACK = 0x808,
	MSG_CODE_SHOW_CONFIG = 0x809,
	MSG_CODE_SHOW_CONFIG_ACK = 0x80a,
	MSG_CODE_SET_USER = 0x80b,
	MSG_CODE_SET_USER_ACK = 0x80c,
	MSG_CODE_SAVE_CONFIG = 0x80d,
	MSG_CODE_SAVE_CONFIG_ACK = 0x80e,
 	MSG_CODE_SHOW_RULE = 0x811,
	MSG_CODE_SHOW_RULE_ACK = 0x812,
	MSG_CODE_REBOOT_SYSTEM = 0x813,
	MSG_CODE_REBOOT_SYSTEM_ACK = 0x814,
	MSG_CODE_SET_USER_ACTIVE = 0x815,
	MSG_CODE_SET_USER_ACTIVE_ACK = 0x816,
	MSG_CODE_RESET_USER_PASSWD = 0x817,
	MSG_CODE_RESET_USER_PASSWD_ACK = 0x818,
	MSG_CODE_SET_USER_LOGINTOOL = 0x819,
	MSG_CODE_SET_USER_LOGINTOOL_ACK = 0x81a,
	MSG_CODE_RESTORE_CONFIG = 0x81b,
	MSG_CODE_RESTORE_CONFIG_ACK = 0x81c,
	MSG_CODE_SHOW_USER_PASSWD = 0x81d,
	MSG_CODE_SHOW_USER_PASSWD_ACK = 0x81e,
	MSG_CODE_SHOW_USER_ACCESS = 0x81f,
	MSG_CODE_SHOW_USER_ACCESS_ACK = 0x820,
 	MSG_CODE_SET_CONNECT_MAX = 0x823,
	MSG_CODE_SET_CONNECT_MAX_ACK = 0x824,
	MSG_CODE_SHOW_CONNECT_MAX = 0x825,
	MSG_CODE_SHOW_CONNECT_MAX_ACK = 0x826,
	MSG_CODE_SET_REAL_TIME_BACKUP = 0x827,
	MSG_CODE_SET_REAL_TIME_BACKUP_ACK = 0x828,
	MSG_CODE_SHOW_AUTOBIND_STATUS = 0x829,
	MSG_CODE_SHOW_AUTOBIND_STATUS_ACK = 0x82a,
 	MSG_CODE_SHOW_RULE_BY_TYPE = 0x82b,
	MSG_CODE_SHOW_RULE_BY_TYPE_ACK = 0x82c,
 	MSG_CODE_SHOW_RULE_HIT_BY_TYPE = 0x82d,
	MSG_CODE_SHOW_RULE_HIT_BY_TYPE_ACK = 0x82e,

	MSG_CODE_SET_TRUSTED_HOSTIP_ABLE = 0x831,
	MSG_CODE_SET_TRUSTED_HOSTIP_ABLE_ACK = 0x832,
	MSG_CODE_ADD_TRUSTED_HOSTIP = 0x833,
	MSG_CODE_ADD_TRUSTED_HOSTIP_ACK = 0x834,
	MSG_CODE_DEL_TRUSTED_HOSTIP = 0x835,
	MSG_CODE_DEL_TRUSTED_HOSTIP_ACK = 0x836,
	MSG_CODE_SET_NTP = 0x837, 
	MSG_CODE_SET_NTP_ACK = 0x838, 
	MSG_CODE_SHOW_NTP_CONFIG = 0x839,
	MSG_CODE_SHOW_NTP_CONFIG_ACK = 0x83a,

 	MSG_CODE_SHOW_AIR_FAN_STATUS = 0X83d,
	MSG_CODE_SHOW_AIR_FAN_STATUS_ACK = 0X83e,
    MSG_CODE_SHOW_POWER_STATUS = 0X83f,
    MSG_CODE_SHOW_POWER_STATUS_ACK = 0X840,

	MSG_CODE_SYNC_FROM_WEB = 0x841,
	MSG_CODE_SYNC_FROM_WEB_ACK = 0x842,

 	MSG_CODE_SET_TEMPERATURE = 0X843,
	MSG_CODE_SET_TEMPERATURE_ACK = 0X844,
 
	MSG_CODE_SET_CHASSIS_FAN_LEVEL = 0x84d,
	MSG_CODE_SET_CHASSIS_FAN_LEVEL_ACK = 0x84e,
	MSG_CODE_SHOW_CHASSIS_FAN_LEVEL = 0x84f,
	MSG_CODE_SHOW_CHASSIS_FAN_LEVEL_ACK = 0x850,
	MSG_CODE_SET_PORT_SWITCH_MODE = 0x851,
	MSG_CODE_SET_PORT_SWITCH_MODE_ACK = 0x852,
	MSG_CODE_SHOW_PORT_SWITCH_MODE = 0x853,
	MSG_CODE_SHOW_PORT_SWITCH_MODE_ACK = 0x854,
	MSG_CODE_SET_SUBSYSTEM_SYSTEM_MODE = 0x855,
	MSG_CODE_SET_SUBSYSTEM_SYSTEM_MODE_ACK = 0x856,

	MSG_CODE_SET_USER_DESCR = 0x857,
	MSG_CODE_SET_USER_DESCR_ACK = 0x858,

    MSG_CODE_SET_DPT_DD_MODE_ABLE = 0x859,
    MSG_CODE_SET_DPT_DD_MODE_ABLE_ACK = 0x85a,

	MSG_CODE_ADD_NODE_APP_URL = 0x860,
	MSG_CODE_ADD_NODE_APP_URL_ACK = 0x861,
	MSG_CODE_ADD_OM_APP_URL = 0x862,
	MSG_CODE_ADD_OM_APP_URL_ACK = 0x863,
	MSG_CODE_DEL_NODE_APP_VERSION = 0x864,
	MSG_CODE_DEL_NODE_APP_VERSION_ACK = 0x865,
	MSG_CODE_DEL_OM_APP_VERSION = 0x866,
	MSG_CODE_DEL_OM_APP_VERSION_ACK = 0x867,
	MSG_CODE_SET_SLOT_APP_ABLE = 0x868,
	MSG_CODE_SET_SLOT_APP_ABLE_ACK = 0x869,
	MSG_CODE_SET_OM_APP_ABLE = 0x86a,
	MSG_CODE_SET_OM_APP_ABLE_ACK = 0x86b,
	MSG_CODE_SHOW_NODE_APP_VERSION = 0x870,
	MSG_CODE_SHOW_NODE_APP_VERSION_ACK = 0x871,
	MSG_CODE_SHOW_OM_APP_VERSION = 0x872,
	MSG_CODE_SHOW_OM_APP_VERSION_ACK = 0x873,
	MSG_CODE_UPDATE_OM_BOTTOM_APP = 0x874,
	MSG_CODE_UPDATE_OM_BOTTOM_APP_ACK = 0x875,
	MSG_CODE_UPDATE_NODE_BOTTOM_APP = 0x876,
	MSG_CODE_UPDATE_NODE_BOTTOM_APP_ACK = 0x877,
	MSG_CODE_GET_UPDATE_APP_RESULT = 0x878,
	MSG_CODE_GET_UPDATE_APP_RESULT_ACK = 0x879,
	MSG_CODE_SHOW_AVAILABLE_APP_VERSION = 0x87a,
	MSG_CODE_SHOW_AVAILABLE_APP_VERSION_ACK = 0x87b,
 
	MSG_CODE_GET_SYNC_FROM_WEB_STATUS = 0x87c,
	MSG_CODE_GET_SYNC_FROM_WEB_STATUS_ACK = 0x87d,

	MSG_CODE_SET_CHASSIS_IP = 0x884,
	MSG_CODE_SET_CHASSIS_IP_ACK = 0x885,
	MSG_CODE_SET_CHASSIS_NUM = 0x886,
	MSG_CODE_SET_CHASSIS_NUM_ACK = 0x887,
    MSG_CODE_SHOW_CHASSIS_STATUS = 0x888,
    MSG_CODE_SHOW_CHASSIS_STATUS_ACK = 0x889,
    MSG_CODE_GET_CHASSIS_NUM = 0x88a,
    MSG_CODE_GET_CHASSIS_NUM_ACK = 0x88b,
    MSG_CODE_GET_CHASSIS_IP = 0x88c,
    MSG_CODE_GET_CHASSIS_IP_ACK = 0x88d,
    MSG_CODE_GET_CHASSIS_SUBSYSTEM_INFO = 0x88e,
    MSG_CODE_GET_CHASSIS_SUBSYSTEM_INFO_ACK = 0x88f,
    MSG_CODE_SET_CHASSIS_DESCR = 0x890,
    MSG_CODE_SET_CHASSIS_DESCR_ACK = 0x891,
    MSG_CODE_GET_CHASSIS_DESCR = 0x892,
    MSG_CODE_GET_CHASSIS_DESCR_ACK = 0x893,
    MSG_CODE_SET_CHASSIS_IP_MORE = 0x894,
    MSG_CODE_SET_CHASSIS_IP_MORE_ACK = 0x895,
    MSG_CODE_CLEAR_CHASSIS_IP_MORE = 0x896,
    MSG_CODE_CLEAR_CHASSIS_IP_MORE_ACK = 0x897,
    MSG_CODE_SET_CHASSIS_MODE = 0x898,
    MSG_CODE_SET_CHASSIS_MODE_ACK = 0x899,
    MSG_CODE_SET_CHASSIS_OUTGROUP = 0x89a,
    MSG_CODE_SET_CHASSIS_OUTGROUP_ACK = 0x89b,
    MSG_CODE_SET_DPT_ERROR_CONTINUE = 0x89c,
    MSG_CODE_SET_DPT_ERROR_CONTINUE_ACK = 0x89d,

	MSG_CODE_SET_SNMP_CHASSIS_IP = 0x8a0,
	MSG_CODE_SET_SNMP_CHASSIS_IP_ACK = 0x8a1,
    MSG_CODE_SET_SNMP_CHASSIS_DESCR = 0x8a2,
    MSG_CODE_SET_SNMP_CHASSIS_DESCR_ACK = 0x8a3,
    MSG_CODE_CLEAR_SNMP_CHASSIS_IP_MORE = 0x8a4,
    MSG_CODE_CLEAR_SNMP_CHASSIS_IP_MORE_ACK = 0x8a5,
    MSG_CODE_GET_SNMP_CHASSIS_INFO = 0x8a6,
    MSG_CODE_GET_SNMP_CHASSIS_INFO_ACK = 0x8a7,
    MSG_CODE_SET_SNMP_CHASSIS_IF_DESCR = 0x8a8,
    MSG_CODE_SET_SNMP_CHASSIS_IF_DESCR_ACK = 0x8a9,
    MSG_CODE_GET_SNMP_CHASSIS_IF_DESCR = 0x8aa,
    MSG_CODE_GET_SNMP_CHASSIS_IF_DESCR_ACK = 0x8ab,
    MSG_CODE_SET_SNMP_CHASSIS_IF_SMAC = 0x8ac,
    MSG_CODE_SET_SNMP_CHASSIS_IF_SMAC_ACK = 0x8ad,
    MSG_CODE_GET_SNMP_CHASSIS_IF_SMAC = 0x8ae,
    MSG_CODE_GET_SNMP_CHASSIS_IF_SMAC_ACK = 0x8af,
    MSG_CODE_SET_SNMP_CHASSIS_IF_DMAC = 0x8b0,
    MSG_CODE_SET_SNMP_CHASSIS_IF_DMAC_ACK = 0x8b1,
    MSG_CODE_GET_SNMP_CHASSIS_IF_DMAC = 0x8b2,
    MSG_CODE_GET_SNMP_CHASSIS_IF_DMAC_ACK = 0x8b3,

	MSG_CODE_SHOW_USER_RESOURCE_ALLOCATION = 0x901,
	MSG_CODE_SHOW_USER_RESOURCE_ALLOCATION_ACK = 0x902,
	MSG_CODE_ADD_RULE = 0x903,
	MSG_CODE_ADD_RULE_ACK = 0x904,
	MSG_CODE_DEL_RULE = 0x905,
	MSG_CODE_DEL_RULE_ACK = 0x906,
	MSG_CODE_CHECK_RULE = 0x907,
	MSG_CODE_CHECK_RULE_ACK = 0x908,
	MSG_CODE_SET_IP_SEARCH_MODE = 0x909,
	MSG_CODE_SET_IP_SEARCH_MODE_ACK = 0x90a,
    MSG_CODE_SET_VLAN_SEARCH_MODE = 0x90b,
    MSG_CODE_SET_VLAN_SEARCH_MODE_ACK = 0x90c,

	MSG_CODE_SET_NOMASK_RULE_COMPLEX = 0x90d,
	MSG_CODE_SET_NOMASK_RULE_COMPLEX_ACK = 0x90e,
	MSG_CODE_ALLOC_RULE_ENTRYNUM_APPLY = 0x90f,
	MSG_CODE_ALLOC_RULE_ENTRYNUM_APPLY_ACK = 0x910,
	MSG_CODE_ALLOC_RULE_ENTRYNUM_DEFAULT = 0x911,
	MSG_CODE_ALLOC_RULE_ENTRYNUM_DEFAULT_ACK = 0x912,
	MSG_CODE_ALLOC_USER_RULE_TYPE_ENTRYNUM = 0x913,
	MSG_CODE_ALLOC_USER_RULE_TYPE_ENTRYNUM_ACK = 0x914,
	MSG_CODE_SET_FLOAT_UD_RULE_APPLY = 0x915,
	MSG_CODE_SET_FLOAT_UD_RULE_APPLY_ACK = 0x916,
	MSG_CODE_SHOW_RULE_NOMASK_CONFIG = 0x917,
	MSG_CODE_SHOW_RULE_NOMASK_CONFIG_ACK = 0x918,

    MSG_CODE_GET_RULE_HIT_NUM_BY_CUS_RID = 0x919,
    MSG_CODE_GET_RULE_HIT_NUM_BY_CUS_RID_ACK = 0x91a,
    MSG_CODE_GET_PORT_FLOW_TRAP = 0x91b,
    MSG_CODE_GET_PORT_FLOW_TRAP_ACK = 0x91c,

    MSG_CODE_SHOW_USER_RULE_HIT_NUM = 0x925,
	MSG_CODE_SHOW_USER_RULE_HIT_NUM_ACK = 0x926,
	MSG_CODE_CLEAR_RULE_HIT_NUM = 0x927,
	MSG_CODE_CLEAR_RULE_HIT_NUM_ACK = 0x928,
    MSG_CODE_GET_CAM_INIT_RESULT = 0x929,
    MSG_CODE_GET_CAM_INIT_RESULT_ACK = 0x92a,
    MSG_CODE_GET_CAM_APPLY_RESULT = 0x92b,
    MSG_CODE_GET_CAM_APPLY_RESULT_ACK = 0x92c,
	MSG_CODE_DEL_RULE_ID = 0x931,
	MSG_CODE_DEL_RULE_ID_ACK = 0x932,
	MSG_CODE_SET_STRING_RULE_MINLEN = 0x939,
	MSG_CODE_SET_STRING_RULE_MINLEN_ACK = 0x93a,

	MSG_CODE_CHECK_RULE_ID = 0x93b,
	MSG_CODE_CHECK_RULE_ID_ACK = 0x93c,

    MSG_CODE_SET_STRING_RULE_APPLY = 0x93d,
	MSG_CODE_SET_STRING_RULE_APPLY_ACK = 0x93e,
	MSG_CODE_SET_RULE_SAFE_MODE = 0x93f,
	MSG_CODE_SET_RULE_SAFE_MODE_ACK = 0x940,
	MSG_CODE_SET_RULE_SAFE_FLOW_THRESHOLD = 0x941,
	MSG_CODE_SET_RULE_SAFE_FLOW_THRESHOLD_ACK = 0x942,

	MSG_CODE_SET_MAX_DPT_RULE_ID = 0x945,
	MSG_CODE_SET_MAX_DPT_RULE_ID_ACK = 0x946,

	MSG_CODE_START_RULE = 0x947,
	MSG_CODE_START_RULE_ACK = 0x948,
	MSG_CODE_STOP_RULE = 0x949,
	MSG_CODE_STOP_RULE_ACK = 0x94a,
	MSG_CODE_SET_RULE_AGING_ABLE = 0x94b,
	MSG_CODE_SET_RULE_AGING_ABLE_ACK = 0x94c,
	MSG_CODE_SHOW_USER_UUID_INFO = 0x94d,
	MSG_CODE_SHOW_USER_UUID_INFO_ACK = 0x94e,
	MSG_CODE_SHOW_USER_RULE_INFO = 0x94f,
	MSG_CODE_SHOW_USER_RULE_INFO_ACK = 0x950,
    MSG_CODE_SHOW_USER_RULE_COUNTER_INFO = 0x951,
    MSG_CODE_SHOW_USER_RULE_COUNTER_INFO_ACK = 0x952,
    MSG_CODE_SHOW_USER_ALL_DPT_RULE_ID = 0x953,
    MSG_CODE_SHOW_USER_ALL_DPT_RULE_ID_ACK = 0x954,
	MSG_CODE_SHOW_USER_TASK_RULE_INFO = 0x955,
	MSG_CODE_SHOW_USER_TASK_RULE_INFO_ACK = 0x956,

    MSG_CODE_SET_INTERFACE_FORCE_UP = 0xa01,
    MSG_CODE_SET_INTERFACE_FORCE_UP_ACK = 0xa02,
    MSG_CODE_SET_INTERFACE_FLOW_THRESHOLD = 0xa03,
    MSG_CODE_SET_INTERFACE_FLOW_THRESHOLD_ACK = 0xa04,
    MSG_CODE_GET_INTERFACE_PERMIT = 0xa05,
    MSG_CODE_GET_INTERFACE_PERMIT_ACK = 0xa06,
	
    MSG_CODE_ALLOC_USER_OUTPORT = 0xb00, 
    MSG_CODE_ALLOC_USER_OUTPORT_ACK = 0xb01, 
    MSG_CODE_ALLOC_USER_OUTPORT_NONE = 0xb02, 
    MSG_CODE_ALLOC_USER_OUTPORT_NONE_ACK = 0xb03, 
	MSG_CODE_ADD_OUTGROUP = 0xb04, 
	MSG_CODE_ADD_OUTGROUP_ACK = 0xb05, 
	MSG_CODE_DEL_OUTGROUP = 0xb06, 
	MSG_CODE_DEL_OUTGROUP_ACK = 0xb07, 
	MSG_CODE_DEL_OUTGROUP_ALL = 0xb08, 
	MSG_CODE_DEL_OUTGROUP_ALL_ACK = 0xb09,
	MSG_CODE_SET_OUTGROUP_HASHMODE = 0xb0a, 
	MSG_CODE_SET_OUTGROUP_HASHMODE_ACK = 0xb0b, 
	MSG_CODE_SET_ACTION_HASHMODE_OUTGROUP = 0xb0c,
	MSG_CODE_SET_ACTION_HASHMODE_OUTGROUP_ACK = 0xb0d,
	MSG_CODE_DEFAULT_ACTION = 0xb0e, 
	MSG_CODE_DEFAULT_ACTION_ACK = 0xb0f, 


    MSG_CODE_SET_USER_AUTOBIND_ENABLE = 0xb30, 
    MSG_CODE_SET_USER_AUTOBIND_ENABLE_ACK = 0xb31, 
    MSG_CODE_SET_USER_AUTOBIND_AGING_TIME = 0xb32, 
    MSG_CODE_SET_USER_AUTOBIND_AGING_TIME_ACK = 0xb33, 
	MSG_CODE_SET_AUTOBIND_MAX_NUM = 0xb34,
	MSG_CODE_SET_AUTOBIND_MAX_NUM_RES = 0xb35,
	MSG_CODE_SET_USER_AUTOBIND_TABLE_ID = 0xb36,
	MSG_CODE_SET_USER_AUTOBIND_TABLE_ID_ACK = 0xb37,
	MSG_CODE_SET_AUTOBIND_TRAP_SCAN_TIME = 0xb38,
	MSG_CODE_SET_AUTOBIND_TRAP_SCAN_TIME_ACK = 0xb39,
	MSG_CODE_SET_USER_AUTOBIND_AGING_ENABLE = 0xb3a, 
	MSG_CODE_SET_USER_AUTOBIND_AGING_ENABLE_ACK = 0xb3b, 
    MSG_CODE_CLEAR_AUTOBIND_REAL_NUM = 0xb3c,
    MSG_CODE_CLEAR_AUTOBIND_REAL_NUM_ACK = 0xb3d,
    MSG_CODE_SET_AUTOBIND_MAX_FW_PACKET = 0xb3e,
    MSG_CODE_SET_AUTOBIND_MAX_FW_PACKET_ACK = 0xb3f,
    MSG_CODE_SHOW_AUTOBIND_REAL_NUM = 0xb40,
    MSG_CODE_SHOW_AUTOBIND_REAL_NUM_ACK = 0xb41,
    MSG_CODE_SHOW_USER_AUTOBIND_STATUS = 0xb42,
    MSG_CODE_SHOW_USER_AUTOBIND_STATUS_ACK = 0xb43,
    MSG_CODE_SET_AUTOBIND_MAX_FW_PACKET_ABLE = 0xb44,
    MSG_CODE_SET_AUTOBIND_MAX_FW_PACKET_ABLE_ACK = 0xb45,

	MSG_CODE_SET_STRIP_HEAD_ENABLE = 0xb50, 
	MSG_CODE_SET_STRIP_HEAD_ENABLE_ACK = 0xb51,
    MSG_CODE_SET_ALL_OUTGROUP_HASHMODE = 0xb52,
    MSG_CODE_SET_ALL_OUTGROUP_HASHMODE_ACK = 0xb53,
    MSG_CODE_SET_USER_HASHMODE = 0xb54,
    MSG_CODE_SET_USER_HASHMODE_ACK = 0xb55,
    MSG_CODE_SET_ACTION_FW_FRONT = 0xb56,
    MSG_CODE_SET_ACTION_FW_FRONT_ACK = 0xb57,
    MSG_CODE_ADD_INGROUP = 0xb58, 
    MSG_CODE_ADD_INGROUP_ACK = 0xb59, 
    MSG_CODE_DEL_INGROUP = 0xb5a, 
    MSG_CODE_DEL_INGROUP_ACK = 0xb5b, 
    MSG_CODE_DEL_INGROUP_ALL = 0xb5c, 
    MSG_CODE_DEL_INGROUP_ALL_ACK = 0xb5d,

	MSG_CODE_SET_DEBUG_LEVEL = 0xc01, 
	MSG_CODE_SET_DEBUG_LEVEL_ACK = 0xc02, 
    MSG_CODE_SET_DEBUG_PRINT = 0xc03,
    MSG_CODE_SET_DEBUG_PRINT_ACK = 0xc04,
    MSG_CODE_SET_DEBUG_FILE = 0xc05,
    MSG_CODE_SET_DEBUG_FILE_ACK = 0xc06,
    MSG_CODE_SHOW_DEBUG_CONFIG = 0xc07,
    MSG_CODE_SHOW_DEBUG_CONFIG_ACK = 0xc08,
    MSG_CODE_SET_DEBUG_DATA = 0xc09,
    MSG_CODE_SET_DEBUG_DATA_ACK = 0xc0a,
    MSG_CODE_SHOW_DEBUG_DATA = 0xc0b,
    MSG_CODE_SHOW_DEBUG_DATA_ACK = 0xc0c,
	MSG_CODE_SHOW_DEBUG_PUB_RULE_NUM = 0xc0d,
	MSG_CODE_SHOW_DEBUG_PUB_RULE_NUM_ACK = 0xc0e,
	MSG_CODE_SET_DEBUG_PUB_RULE_NUM = 0xc0f,
	MSG_CODE_SET_DEBUG_PUB_RULE_NUM_ACK = 0Xc10,
	MSG_CODE_SHOW_TABLE_ENTRY_NUMBER = 0xc11,
	MSG_CODE_SHOW_TABLE_ENTRY_NUMBER_ACK = 0xc12,
	MSG_CODE_SHOW_DEBUG_OUTGROUP_HIT_NUM = 0xc13,
	MSG_CODE_SHOW_DEBUG_OUTGROUP_HIT_NUM_ACK = 0xc14,
	MSG_CODE_SHOW_DEBUG_ACTION_HIT_NUM = 0xc15,
	MSG_CODE_SHOW_DEBUG_ACTION_HIT_NUM_ACK = 0xc16,
	MSG_CODE_CLEAR_DEBUG_ACTION_HIT_NUM = 0xc17,
	MSG_CODE_CLEAR_DEBUG_ACTION_HIT_NUM_ACK = 0xc18,
	MSG_CODE_SET_DEBUG_RULE_RANK_SORT_ABLE = 0xc19,
	MSG_CODE_SET_DEBUG_RULE_RANK_SORT_ABLE_ACK = 0xc1a,
	MSG_CODE_SHOW_SYNC_STATUS = 0xc1b,
	MSG_CODE_SHOW_SYNC_STATUS_ACK = 0xc1c,
	MSG_CODE_SET_DEBUG_FILE_SIZE = 0xc1d,
	MSG_CODE_SET_DEBUG_FILE_SIZE_ACK = 0xc1e,

	MSG_CODE_SHOW_USER_LOG = 0xd01,
	MSG_CODE_SHOW_USER_LOG_ACK = 0xd02,
	MSG_CODE_SET_LOG_TIMEFORMAT = 0xd03,
	MSG_CODE_SET_LOG_TIMEFORMAT_ACK = 0xd04,
	MSG_CODE_SET_LOG_MIBINFO = 0xd05,
	MSG_CODE_SET_LOG_MIBINFO_ACK = 0xd06,
	MSG_CODE_SET_LOG_FILESIZE = 0xd07,
	MSG_CODE_SET_LOG_FILESIZE_ACK = 0xd08,
	MSG_CODE_SET_LOG_FTP = 0xd09,
	MSG_CODE_SET_LOG_FTP_ACK = 0xd0a,
	MSG_CODE_SET_LOG_SYSLOG = 0xd0b,
	MSG_CODE_SET_LOG_SYSLOG_ACK = 0xd0c,
	MSG_CODE_SET_LOG_ENABLE = 0xd0d,
	MSG_CODE_SET_LOG_ENABLE_ACK = 0xd0e,
	MSG_CODE_SHOW_LOG_CONFIG = 0xd0f,
	MSG_CODE_SHOW_LOG_CONFIG_ACK = 0xd10,
	MSG_CODE_SET_TRAP_LOG_EN_SW = 0xd11,
	MSG_CODE_SET_TRAP_LOG_EN_SW_ACK = 0xd12,

	MSG_CODE_SET_SNMP_OPTION = 0xe01,
	MSG_CODE_SET_SNMP_OPTION_ACK = 0xe02,
	MSG_CODE_SHOW_SNMP_STATUS = 0xe03,
	MSG_CODE_SHOW_SNMP_STATUS_ACK = 0xe04,
	MSG_CODE_SHOW_SNMP_CONFIG = 0xe05,
	MSG_CODE_SHOW_SNMP_CONFIG_ACK = 0xe06,
	MSG_CODE_SET_SNMP_CONFIG = 0xe07,
	MSG_CODE_SET_SNMP_CONFIG_ACK = 0xe08,


	RCP_NISAC_MSG_CODE_SHOW_SYSTEM = 0xf01,
	RCP_NISAC_MSG_CODE_SHOW_SYSTEM_ACK = 0xf02,
	RCP_NISAC_MSG_CODE_SHOW_CONFIG = 0xf0d,
	RCP_NISAC_MSG_CODE_SHOW_CONFIG_ACK = 0xf0e,
	RCP_NISAC_MSG_CODE_SHOW_USER_LOG = 0xf0f,
	RCP_NISAC_MSG_CODE_SHOW_USER_LOG_ACK = 0xf10,
	RCP_NISAC_MSG_CODE_RESTORE_CONFIG = 0xf11,
	RCP_NISAC_MSG_CODE_RESTORE_CONFIG_ACK = 0xf12,
    MSG_CODE_SET_SYSTEM_HASH = 0xf13,
    MSG_CODE_SET_SYSTEM_HASH_ACK = 0xf14,

	MSG_CODE_END
} msg_code_e;

typedef enum _msg_block_type_e { 
    BLOCK_TYPE_START = 0x00, 
    BLOCK_RCP_NISAC_IPV4_FIVE_TUPLE = 0x01, 
    BLOCK_RCP_NISAC_IPV6_FIVE_TUPLE = 0x02, 
    BLOCK_RCP_NISAC_TCP_FLAG_PAYLOAD_LEN = 0x03, 
    BLOCK_RCP_NISAC_UD = 0x04,

    BLOCK_RCP_NISAC_IPV4_FIVE_TUPLE_QUERY_RES = 0x07, 
    BLOCK_RCP_NISAC_IPV6_FIVE_TUPLE_QUERY_RES = 0x08, 
    BLOCK_RCP_NISAC_TCP_FLAG_PAYLOAD_LEN_QUERY_RES = 0x09, 
    BLOCK_RCP_NISAC_UD_QUERY_RES = 0x0A,

    BLOCK_RCP_NISAC_USER_AUTH = 0x0C, 
    BLOCK_RCP_NISAC_RESULT_CODE = 0x0D,

    BLOCK_RCP_NISAC_RULE_NUM = 0x0F,

    BLOCK_CLI_USER_REG = 0x20, 
    BLOCK_CLI_RESULT_CODE = 0x21, 
    BLOCK_SLOT = 0x22, 
    BLOCK_USER_PASSWD = 0x23, 
    BLOCK_USER_ID = 0x24, 
    BLOCK_RULE = 0x25, 
    BLOCK_IP_SEARCH_MODE = 0x26, 

    BLOCK_NOMASK_RULE_COMPLEX = 0x28, 

    BLOCK_IF_TYPE = 0x2B, 
    BLOCK_IF_SMP = 0x2C, 

    BLOCK_OUTGROUP = 0x34, 
    BLOCK_USER_OUTPORT = 0x35, 

    BLOCK_USER_RULE_TYPE_ENTRYNUM = 0x37, 
    BLOCK_USER_INFO = 0x38,
    BLOCK_OUTGROUP_HASHMODE = 0x39, 

    BLOCK_AUTOBIND = 0x3c,
    BLOCK_FWHEAD_SCALE = 0x3d,

    BLOCK_USER_LOGINTOOL = 0x40,
    BLOCK_SNMP_CONFIG = 0x41,
    BLOCK_LOG_SHOW_FILTER = 0x42,
    BLOCK_LOG_CONFIG = 0x43,
    BLOCK_DATA_FLAG = 0x44,

    BLOCK_COMMON_ENABLE = 0x46,

    BLOCK_SYSTEM_INFO = 0x51,

    BLOCK_VERSION = 0x5a,
    BLOCK_PORT_SWITCH_MODE = 0x5b,
    BLOCK_PORT_FLEXIBLE_MODE = 0x5c,
    BLOCK_PORT_SWITCH_MODE_ALL = 0x5d,
    BLOCK_CLI_RESULT_REASON = 0x5e,
    BLOCK_ACTION = 0x5f,
    BLOCK_CHASSIS_IP_INFO = 0x61,
    BLOCK_RULE_ID = 0x62,
    BLOCK_CHASSIS_ATTR = 0x63,

    BLOCK_RESULT_CODE_RULE = 0x70,
    BLOCK_RULE_HIT_NUM = 0x71,
    BLOCK_PORT_FLOW_TRAP = 0x72,

    BLOCK_CHASSIS_IF_DESCR = 0x73,
    BLOCK_CHASSIS_IF_MAC = 0x74,
    BLOCK_USER_TASK_ID = 0x75, 
    BLOCK_RULE_WITH_HIT = 0x76, 

    BLOCK_TYPE_END
} msg_block_type_e;

#define register_msg_header(flag, cmd,  msg_type, msg_code, msg_block_type) 

//------------------------------------------------      ADD RULE     --------------------------------------------------------------------------------
//add rule inner_rule_id= <class_entry> action <action_id> [front] customer_rule_id= uuid= <aging_type> <hit_flag> <dynamic_flag> <sdd_flag> taskid= 加规则
//ADD RULE inner_id class_entry substring_entry ACTION action_id front customer_id user_uid optional_flag task_id EOS
//使用的结构体是 struct Rule_B;

register_msg_header(RCP_NISAC_V3, ADD_RULE, MSG_TYPE_CLI_RULE, MSG_CODE_ADD_RULE, BLOCK_RULE);

#define UD_NUM 39
#define MAX_ONE_STRING_NUM 4
#define MAX_STRING_BUFFER_LEN 128

struct rule_size_t{//4
	unsigned short min_size;
	unsigned short max_size;	
};

struct ow_ud_t {//4
	unsigned short data;
	unsigned short mask;
};

struct ow_string_t {//138
    char string_buffer[MAX_STRING_BUFFER_LEN+1]; 
    uint16_t string_hex_flag;
    uint16_t string_offset_type; //0:float; 1:fix
    uint16_t string_offset_start;
    uint16_t string_offset_end;
};

struct string_entry_t{ //556
	uint32_t se_mask;
	struct ow_string_t string_entrys[MAX_ONE_STRING_NUM];
};

struct phone_entry_t{ //16
	int			type;
	uint64_t	value;
};

struct ow_cli_sys_info_t {//56
    uint32_t cuid;
    uint8_t rule_type;
    uint8_t save;       //  dynamic rule use, 2 string, 3 combine
    uint8_t safe;
    uint8_t ori_is_nomask;
    uint8_t action; //0:drop, 1:fw
    uint8_t user_id;
    uint8_t rule_flag;
    uint8_t aging_type;
    uint8_t is_front;
    uint16_t action_id;
    uint32_t aging_flow;
    uint32_t aging_time;
    uint32_t inner_rule_id;
    uint32_t nvi_rule_id;
    uint32_t customer_rule_id;
    uint32_t rule_config_time;	//from 1970.0101 0hour 0second
    uint32_t host_ip;
    uint8_t dynamic_bind_flag;
    uint16_t dynamic_bind_pattern;
    uint8_t valid;
    uint32_t taskid;
};

struct class_entry_cli_t { //928
    unsigned int size;
    unsigned int key_mask;
    unsigned int protocol;
    unsigned int protocol_mask;
    unsigned int sip;
    unsigned int sip_mask;
    unsigned int dip;
    unsigned int dip_mask;
    unsigned short sport;
    unsigned short sport_mask;
    unsigned short dport;
    unsigned short dport_mask;
    unsigned short tcp_flag;
    struct rule_size_t size_range;   //for fpga
    unsigned short sipv6[8];
    unsigned short sipv6_mask[8];
    unsigned short dipv6[8];
    unsigned short dipv6_mask[8];
    unsigned short ip_version;	//0: ipv4,1:ipv6  
    long long ud_mask;
    struct ow_ud_t uds[UD_NUM];
    unsigned int grp_key;
    unsigned int grp_key_mask;
    unsigned int vlan_id;
    struct string_entry_t string_entry;
    struct phone_entry_t phone_entry;
    unsigned char ingroup;
    struct ow_cli_sys_info_t sys_info;
};

struct Rule_B {  //936
	struct class_entry_cli_t class_entry;
	RCP_UINT32 outgroup_id;
};

//------------------------------------------------      DELETE RULE     --------------------------------------------------------------------------------
//delete rule <class_entry> uuid= 根据规则内容删除
//DELETE RULE class_entry substring_entry user_uid optional_flag EOS
//使用的结构体是 struct Rule_B;

register_msg_header(RCP_NISAC_V3, DEL_RULE, MSG_TYPE_CLI_RULE, MSG_CODE_DEL_RULE, BLOCK_RULE);

// struct Rule_B {  //936
// 	struct class_entry_cli_t class_entry;
// 	RCP_UINT32 outgroup_id;
// };

//------------------------------------------------      DELETE RULE     --------------------------------------------------------------------------------
//delete rule customer_rule_id= uuid= 根据规则id删除
//DELETE RULE customer_rule_id user_uid EOS
//使用的结构体是 struct RuleID_B;

register_msg_header(RCP_NISAC_V3, DEL_RULE_ID, MSG_TYPE_CLI_RULE, MSG_CODE_DEL_RULE_ID, BLOCK_RULE_ID);

struct RuleID_B {//16
    RCP_UINT32 inner_rule_id;
    RCP_UINT32 customer_rule_id;
    RCP_UINT32 cuid;
};

//------------------------------------------------      CHECK RULE     --------------------------------------------------------------------------------
//check rule <class_entry> uuid= 根据规则内容check
//CHECK RULE class_entry substring_entry uuid optional_flag less EOS
//使用的结构体是 struct Rule_B;

register_msg_header(RCP_NISAC_V3, CHECK_RULE, MSG_TYPE_CLI_RULE, MSG_CODE_CHECK_RULE, BLOCK_RULE);

// struct Rule_B {  //936
// 	struct class_entry_cli_t class_entry;
// 	RCP_UINT32 outgroup_id;
// };

//------------------------------------------------      CHECK RULE     --------------------------------------------------------------------------------
//check rule customer_rule_id= uuid= 根据规则id check
//CHECK RULE customer_rule_id uuid less EOS
//使用的结构体是 struct DataFlag_B;

register_msg_header(RCP_NISAC_V3, CHECK_RULE_ID, MSG_TYPE_CLI_RULE, MSG_CODE_CHECK_RULE_ID, BLOCK_DATA_FLAG);

struct DataFlag_B{//20
	RCP_UINT32 data;
	RCP_UINT32 data_2;
	RCP_UINT32 flag;
	RCP_UINT32 val;
    RCP_UINT32 cuid;
};

//------------------------------------------------     SHOW USER     --------------------------------------------------------------------------------
//show user <user_id> taskid _INT_ rule info verbose  （不带verbose server只填充了规则内容，带verbose，会带上规则的命中计数）
//SHOW USER user_id TASKID _INT_ RULE INFO verbose EOS
//使用的结构体是 struct UserTaskId_B;

register_msg_header(RCP_NISAC_V3, SHOW_USER_TASK_RULE_INFO, MSG_TYPE_CLI_RULE, MSG_CODE_SHOW_USER_TASK_RULE_INFO, BLOCK_USER_TASK_ID);

struct UserTaskId_B {//12
	RCP_UINT32 user_id;
	RCP_UINT32 task_id;
	RCP_UINT32 verbose;
};

struct RuleHit_B {
    uint64_t hit_num;
    uint64_t hit_bytes;
    uint64_t rate_bps;
    uint64_t rate_pps;
};

struct RuleWithHit_B {
    struct Rule_B rule;
    struct RuleHit_B hit;
};

int main()
{

	struct RuleWithHit_B* ptr = NULL;
	ptr = realloc(ptr, sizeof(struct RuleWithHit_B));

	char *p = ptr;

	printf("%d\n",p[sizeof(struct RuleWithHit_B) -3]);
    printf("size :%lu\n", sizeof(struct RuleWithHit_B));
}